K8s improvements
Financial-Times/content-collection-unfolder pull request #12
Opened 2017-12-22 11:47 UTC by bogdanguranda

Added timed healthcheck.
Helm: memory requested, memory limit, pod anti affinity.

2017-12-22 12:34 UTC, tosan88 approved these changes

2018-01-08 09:43 UTC, ioanaciont approved these changes

2018-01-08 11:51 UTC, tamas-molnar requested changes
https://upp-k8s-jenkins.in.ft.com/job/k8s-deployment/job/utils/job/deploy-upp-helm-chart/3240/console affinity config is not correct, probably indentation issue

2018-01-09 12:03 UTC, kovacshuni approved these changes

2018-01-09 12:13 UTC, kovacshuni approved these changes

2018-01-09 13:03 UTC, tamas-molnar approved these changes

2018-01-11 08:45 UTC, merged