UPPSF-131 Added parameterised waiting interval in the call to contentResolver (document-store-api) to avoid getting still not existing content there
Financial-Times/content-collection-unfolder pull request #19
Opened 2019-07-24 08:52 UTC by gkazakov111

2019-07-25 08:59 UTC, rnov commented on helm/content-collection-unfolder/app-configs/content-collection-unfolder_delivery.yaml
> +  REQUEST_TIMEOUT: 2
missing eol

2019-07-25 12:34 UTC, rnov commented on resolver/contentResolver.go
> +	defer resp.Body.Close()
missing error handling

2019-07-26 08:06 UTC, rnov commented on main_test.go
> +	requestTimeoutInt           = 2000000000
suggestion: 2e9 might be more verbose ?

2019-07-26 08:46 UTC, rnov requested changes
as we agreed, all defer calls must handle errors a candidates to check  :
```
./forwarder/forwarder.go:48:	defer resp.Body.Close()
./forwarder/forwarder_test.go:35:		defer r.Body.Close()
./forwarder/forwarder_test.go:57:	defer mockServer.Close()
./forwarder/forwarder_test.go:68:	defer mockServer.Close()
./forwarder/forwarder_test.go:80:	defer mockServer.Close()
./relations/relationsResolver_test.go:24:	defer file.Close()
./relations/relationsResolver.go:33:	defer resp.Body.Close()
./healthcheck.go:129:	defer resp.Body.Close()
./common_test.go:50:	defer file.Close()
./unfolder.go:73:	defer req.Body.Close()
./unfolder_test.go:32:	defer server.Close()
./unfolder_test.go:54:	defer server.Close()
./unfolder_test.go:65:	defer resp.Body.Close()
./unfolder_test.go:86:	defer server.Close()
./unfolder_test.go:100:	defer resp.Body.Close()
./unfolder_test.go:127:	defer server.Close()
./unfolder_test.go:151:	defer resp.Body.Close()
./unfolder_test.go:176:	defer server.Close()
./unfolder_test.go:201:	defer resp.Body.Close()
./unfolder_test.go:230:	defer server.Close()
./unfolder_test.go:254:	defer resp.Body.Close()
./unfolder_test.go:285:	defer server.Close()
./unfolder_test.go:315:	defer resp.Body.Close()
./unfolder_test.go:345:	defer server.Close()
./unfolder_test.go:378:	defer resp.Body.Close()
./unfolder_test.go:404:	defer server.Close()
./unfolder_test.go:443:	defer resp.Body.Close()
./unfolder_test.go:461:	defer server.Close()
./unfolder_test.go:485:	defer resp.Body.Close()
./resolver/contentResolver.go:34:	defer resp.Body.Close()
./resolver/contentResolver.go:113:	defer resp.Body.Close()
./resolver/contentResolver_test.go:30:	defer file.Close()
./resolver/uuidResolver_test.go:86:	defer file.Close()
./main_test.go:39:	defer writerServer.Close()
./main_test.go:42:	defer contentResolverServer.Close()
./main_test.go:45:	defer relationsResolverServer.Close()
./main_test.go:52:	defer unfolderServer.Close()
./main_test.go:59:	defer resp.Body.Close()
./main_test.go:79:	defer writerServer.Close()
./main_test.go:82:	defer contentResolverServer.Close()
./main_test.go:85:	defer relationsResolverServer.Close()
./main_test.go:92:	defer unfolderServer.Close()
./main_test.go:99:	defer resp.Body.Close()
./main_test.go:119:	defer writerServer.Close()
./main_test.go:122:	defer contentResolverServer.Close()
./main_test.go:125:	defer relationsResolverServer.Close()
./main_test.go:132:	defer unfolderServer.Close()
./main_test.go:138:	defer resp.Body.Close()
./main_test.go:161:		defer r.Body.Close()
./main_test.go:67:	json.Unmarshal(body, &healthResult)
./main_test.go:107:	json.Unmarshal(body, &healthResult)

```

2019-07-26 08:46 UTC, rnov commented on config.go
> +	requestTimeout             *int
what's the point in general to use pointers for unmutable values like string or ints ?

2019-07-29 12:31 UTC, gkazakov111 commented on helm/content-collection-unfolder/app-configs/content-collection-unfolder_delivery.yaml
> +  REQUEST_TIMEOUT: 2
fixed

2019-07-29 12:31 UTC, gkazakov111 commented on resolver/contentResolver.go
> +	defer resp.Body.Close()
will be fixed generally later

2019-07-29 12:31 UTC, gkazakov111 commented on main_test.go
> +	requestTimeoutInt           = 2000000000
fixed

2019-07-31 07:44 UTC, rnov submitted a review, later dismissed

2019-08-08 10:19 UTC, gotha approved these changes

2019-08-08 10:21 UTC, merged